import LottieView, { type AnimationObject } from 'lottie-react-native';
import { useCallback, useEffect, useRef } from 'react';
import { View } from 'react-native';

/**
 * One of the landing's Lottie scenes (assets/lottie/*.json, generated by
 * landing-page-new/scripts/lottie) on an onboarding slide.
 *
 * - Rests on the scene's "poster" marker frame: that is what a slide shows
 *   while it is off screen or swiping in (frame 0 of most scenes is nearly
 *   empty), and all it ever shows with Reduce Motion.
 * - Plays (looping) only while `active`; leaving the slide pauses it, coming
 *   back resumes from that frame. `play()` resumes from the current frame on
 *   both iOS and Android, so the first play starts at the poster.
 * - `still` (Reduce Motion, or the setting not known yet) never plays. Turning
 *   it on remounts the view, which puts the poster frame back.
 */

/** Normalised progress (0–1) of the scene's "poster" marker; 0.5 without one. */
function posterProgress(source: AnimationObject): number {
  const marker = source.markers?.find((m: { cm?: unknown }) => m?.cm === 'poster') as
    | { tm?: unknown }
    | undefined;
  const span = source.op - source.ip;
  if (!marker || typeof marker.tm !== 'number' || !(span > 0)) return 0.5;
  return Math.min(1, Math.max(0, (marker.tm - source.ip) / span));
}

type Props = {
  source: AnimationObject;
  active: boolean;
  still: boolean;
  width: number;
  height: number;
};

export function OnboardingLottie({ source, active, still, width, height }: Props) {
  const ref = useRef<LottieView>(null);
  const shouldPlay = active && !still;
  const shouldPlayRef = useRef(shouldPlay);

  useEffect(() => {
    shouldPlayRef.current = shouldPlay;
    if (shouldPlay) ref.current?.play();
    else ref.current?.pause();
  }, [shouldPlay]);

  // A command sent before the native view has its composition is dropped on
  // some platforms, so (re)start once it reports loaded.
  const onLoaded = useCallback(() => {
    if (shouldPlayRef.current) ref.current?.play();
  }, []);

  return (
    <View
      style={{ width, height }}
      pointerEvents="none"
      accessibilityElementsHidden
      importantForAccessibility="no-hide-descendants"
    >
      <LottieView
        key={still ? 'still' : 'motion'}
        ref={ref}
        source={source}
        progress={posterProgress(source)}
        autoPlay={false}
        loop
        resizeMode="contain"
        style={{ width, height }}
        onAnimationLoaded={onLoaded}
      />
    </View>
  );
}
