export const COUPON_TITLE_MAX_LENGTH = 18;
export const COUPON_SHORT_DESCRIPTION_MAX_LENGTH = 90;
export const COUPON_DESCRIPTION_MAX_LENGTH = 500;
export const COUPON_TERMS_AND_CONDITION_MAX_LENGTH = 2000;
