apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: houstrac-be
  labels:
    cloud.googleapis.com/location: europe-west1
  annotations:
    run.googleapis.com/launch-stage: BETA
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
    run.googleapis.com/minScale: '1'
spec:
  template:
    metadata:
      labels:
        run.googleapis.com/startupProbeType: Default
      annotations:
        autoscaling.knative.dev/maxScale: '10'
        run.googleapis.com/vpc-access-egress: private-ranges-only
        run.googleapis.com/network-interfaces: '[{"network":"default","subnetwork":"default"}]'
        run.googleapis.com/cloudsql-instances: houstrac-dev:europe-west1:postgres-houstrac-eb153a2b
        run.googleapis.com/client-name: cloud-console
        run.googleapis.com/startup-cpu-boost: 'true'
    spec:
      containerConcurrency: 80
      timeoutSeconds: 300
      serviceAccountName: 703223146266-compute@developer.gserviceaccount.com
      containers:
        - name: houstrac-be-1
          image: europe-west1-docker.pkg.dev/houstrac-dev/houstrac-be/houstrac-be:<TAG>
          ports:
            - name: http1
              containerPort: 4000
          env:
            - name: ENVIRONMENT
              value: PROD
            - name: BE_JWT
            - name: FACEBOOK_APP_SECRET
              value: test
            - name: FACEBOOK_APP_ID
              value: test
            - name: FACEBOOK_CALLBACK
              value: test
            - name: GOOGLE_APP_SECRET
            - name: GOOGLE_APP_ID
            - name: GOOGLE_CALLBACK
              value: https://dev.houstrac.com/authorization/login/google/return
            - name: APPLE_PROFILE
              value: apple
            - name: com.konradhopek.houstrac
              value: test
            - name: APPLE_TEAM_ID
              value: test
            - name: APPLE_KEY_ID
              value: test
            - name: APPLE_CALLBACK
              value: test
            - name: APPLE_CERTIFICATE
              value: test
            - name: FRONT_END_APP_URL
              value: https://app.easybons.com
            - name: FRONT_END_MERCHANT_URL
              value: https://app.easybons.com
            - name: AWS_ACCESS_KEY_ID
            - name: AWS_SECRET_KEY
            - name: AWS_BUCKET_NAME
              value: houstrac
            - name: AWS_S3_SERVER_ENDPOINT
              value: http://s3.eu-central-1.amazonaws.com
            - name: AWS_S3_FILE_CODE
              value: -houstrac__e3221sad-
            - name: BACKEND_HOST
              value: https://dev.houstrac.com/authorization/resetPassword
            - name: SENDGRID_API_KEY
            - name: SENDGRID_FROM
              value: contact@houstrac.com
            - name: FEEDBACK_TO
              value: contact@houstrac.com
            - name: SENTRY_DSN
            - name: BACKEND_ADDRESS
              value: https://dev.houstrac.com
            - name: STRIPE_PUBLISHABLE_KEY
            - name: STRIPE_SECRET_KEY
            - name: STRIPE_API_SECRET
            - name: WEBHOOK_STRIPE
            - name: DATABASE_URL
            - name: GSC_BUCKET_NAME
              value: dev-houstrac-88b4
            - name: GSC_PROJECT_ID
              value: houstrac-dev
            - name: REMOVED_ACCOUNT_AVATAR
              value: https://storage.googleapis.com/dev-houstrac-88b4/1726139099714-houstrac__e3221sad-removepng
            - name: REMOVED_PASSWORD

          resources:
            limits:
              cpu: 1000m
              memory: 512Mi
          startupProbe:
            timeoutSeconds: 240
            periodSeconds: 240
            failureThreshold: 1
            tcpSocket:
              port: 4000
  traffic:
    - percent: 100
      latestRevision: true
