export const STATS_INSIGHT_MAX_PER_SCREEN = 3;

export const STATS_INSIGHT_MIN_STAMP_CARDS = 5;
export const STATS_INSIGHT_MIN_COUPON_CLAIMED = 15;
export const STATS_INSIGHT_MIN_MILESTONES = 4;
export const STATS_INSIGHT_MIN_STREAK_VISITS = 8;

export const STATS_INSIGHT_STAMP_STEP_DROP_WARN = 0.22;
export const STATS_INSIGHT_SHARE_COMPLETED_WARN = 0.12;

export const STATS_INSIGHT_CLAIM_TO_USE_GOOD = 0.58;
export const STATS_INSIGHT_CLAIM_TO_USE_WARN = 0.45;

export const STATS_INSIGHT_REDEMPTION_GAP_PP = 0.14;

export const STATS_INSIGHT_STREAK_CONV_WARN = 0.07;
export const STATS_INSIGHT_STREAK_VS_GLOBAL_GAP = 0.12;

export const STATS_INSIGHT_COMPARE_DELTA_PCT_WARN = -0.12;
