export const MERCHANT_STATS_CARD_SURFACE_CLASS =
  "bg-white rounded-3xl p-4 border border-gray-100-light shadow-settings-card";

export const MERCHANT_STATS_FILTER_SURFACE_CLASS = `${MERCHANT_STATS_CARD_SURFACE_CLASS} gap-5`;

export const MERCHANT_STATS_SECTION_CARD_SURFACE_CLASS = `${MERCHANT_STATS_CARD_SURFACE_CLASS} gap-4`;

export const MERCHANT_STATS_CHART_PRIMARY_BLUE = "#1A4198";

export const MERCHANT_STATS_CHART_HUB_COMPARE_LINE = "#94A3B8";

export const MERCHANT_STATS_CHART_TREND_SECONDARY = "#C7C7CC";
