/**
 * The ten Lottie scenes of the /for-business story.
 *
 * Each name maps 1:1 to `public/lottie/<name>.json`, generated by
 * `npm run lottie:build` from `scripts/lottie/scenes/<name>.mjs`.
 * The generator reads SCENE_NAMES from this file (by regex) and fails the
 * build when the two lists drift apart — keep it a plain string array.
 */
export const SCENE_NAMES = [
  "account",
  "brand",
  "spots",
  "menu",
  "scan",
  "points",
  "rewards",
  "moreOrders",
  "onlineOrders",
  "couriers",
] as const;

export type SceneName = (typeof SCENE_NAMES)[number];

export const STORY_ACTS = [
  { id: "setup", scenes: ["account", "brand", "spots", "menu"] },
  { id: "counter", scenes: ["scan", "points", "rewards"] },
  { id: "beyond", scenes: ["moreOrders", "onlineOrders", "couriers"] },
] as const satisfies readonly { id: string; scenes: readonly SceneName[] }[];

export function isSceneName(value: string): value is SceneName {
  return (SCENE_NAMES as readonly string[]).includes(value);
}
